# Generated by Django 3.2.9 on 2021-11-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniinsta', '0002_auto_20211117_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album',
            field=models.TextField(blank=True, null=True),
        ),
    ]
