# Generated by Django 3.2.9 on 2021-11-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniinsta', '0004_alter_pictures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='category_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
