# Generated by Django 3.2.9 on 2021-11-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniinsta', '0005_pictures_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='category_name',
        ),
    ]
